### ISSUE TITLE
[EPIC] Leftovers from phase b

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#132]
Tasks
- [x] Finish test coverage
  * _MERGED_ https://github.com/Synthetixio/synthetix/pull/804 - Takes SecondaryDeposit coverage to 94.59 (+4.85%)
- [x] (Anton) Split snapshots from Issuer
  * _MERGED_ https://github.com/Synthetixio/SIPs/pull/269 
  * https://github.com/Synthetixio/synthetix/pull/811 , waiting to be reviewed!
- [x] Moved to EPIC #135  ~Send 2.2m SNX to deposit (2 options):~
  * Send directly to SecondaryDeposit and then migrate.
  * Send directly to SynthtixOptimisticBridge (the new contract that deposit is going to be migrated to.
- [x] Moved to EPIC #133 ~Tests in OVM mode (the ones that are super slow)~
  * ~down to one hour (needs the new V2 update)~
- [x] Moved to EPIC #133  ~Multi/docker tests~
  * ~Fixed the same-chain ones instead.~
  * ~Kevin's: https://github.com/Synthetixio/synthetix/pull/787~
- [x] ~Add MintableSynthetix unit tests.~
  * (MERGED) https://github.com/Synthetixio/synthetix/pull/803
