### ISSUE TITLE
[EPIC] OVM compilation, tests and CI improvements

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#133]
### Rationale

The deploy commands (and associated commands) need changes for the upcoming L2 phase c release. However, it has become a bit bloated and out of control. It could use some refactoring to be more stable and easy to maintain, while we introduce these necessary features.

#### Changes
- [x] Improve OVM contract compilation
  * ~_ABANDONED_ [PR: Improve OVM contract compilation](https://github.com/Synthetixio/synthetix/pull/813)~
  * _MERGED_ [PR: Use strict OVM compiler (removes SelfDestructible) #814](https://github.com/Synthetixio/synthetix/pull/814)
- [x] CI job that fails when compilation in either mode fails
  * _MERGED_ PR: [CI compile job](https://github.com/Synthetixio/synthetix/pull/815)
- [x] Protect against the possibility of deploying the wrong compilation artifacts in an OVM/non-OVM network
  * _DONE_ Test what happens when we deploy ovm artifacts in a fork of mainnet - results are inconclusive: ovm in mainnet reverts with no reason when attempting to deploy any contract, mainnet in ovm deploys some contracts, but fails when doing some mutative function calls.
  * _MERGED_ Consider checking metadata, or some sort of watermark for OVM bytecode - [PR: Deploy 
script checks compiled contracts expected compiler version #822](https://github.com/Synthetixio/synthetix/pull/822) Optimism released alpha 4 of the compiler, which contains "ovm" in the compiler version. This PR can be updated to look for that, instead of hardcoding a version.
- [x] (@zyzek) Split Issuer so that it can be compiled for OVM
  * _MERGED_ Implement: [PR: SIP-91 Debt snapshots L2 refactor](https://github.com/Synthetixio/synthetix/pull/811)
  * _DONE_ Don't forget to remove Issuer and related contracts from `ovm-ignored.json`.
