### ISSUE TITLE
[EPIC] Support withdrawals from L2 to L1

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#135]
This epic tracks the tasks needed to be completed before deploying for phase C of the OVM trial that tests withdrawing functionality from L2 to L1.
- [x] (MERGED) Currently everything is updated in this PR : https://github.com/Synthetixio/synthetix/pull/806
  * [x] Fix tests and coverage:
  * [x] (FIXED) same chain multi:test.
  * [x] coverage (>95%).
- [x] Finalize contract renaming and conventions:
  * [x] new contract names: `SynthetixBridgeToBase`, `SynthetixBridgeToOptimistism`.
  * [x] resolver names: we use the `ovm:` and `base:` as prefixes, e.g. `ovm:SynthetixBridgeToBase`
  * [x] Rename `companion()` view function: we can use explicit naming now i.e. synthetixBridgeToOptimism().
- [x] Sync with the  Optimism team regarding their contract upgrade:
  * [x] ask for a new npm package (@eth-optimism/rollup-contracts) to reflect the new contract changes
  * [x] update messenger interfaces (move from rollup-contracts package to contracts, release: 0.0.2-alpha.6).
          (MERGED) https://github.com/Synthetixio/synthetix/pull/825
  * [x] fix same-chain multi-tests.
  * [x] update spec tests: https://github.com/Synthetixio/synthetix/pull/827 (MERGED)
- [x]  `maxDeposit` param should be removed: https://github.com/Synthetixio/synthetix/pull/816 (MERGED).
- [x] Update all L2 related tests to use smock. 
- [x] Support SNX to be deposited in L1 to be claimable on L2 
  * (MERGED) PR: Synthetixio/synthetix#818
- [ ] Run a test release according to Phase C cheatsheet (https://docs.google.com/document/d/13976hTEnLJt3vVTi4Vbh8mQ875dq_T_70uGEQhZYRTc/): 
  * [ ] get the addresses of the new messengers if available before phase C deployment.
  * [ ] handle it to the front end team for testing.
