### ISSUE TITLE
[EPIC] Improve infrastructure and workflow

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#136]
### Rationale

We want to improve the experience for developers working on Synthetix. Atm, the experience is sub-optimal, because CI often produces false negatives that get in the way of things that need to get done. Also, the repository is becoming a "bag for stuff" that covers a wide range of concerns, each of which triggers a complex CI process that is becoming ever more unstable and difficult to maintain. The basic strategy to improve this is to move code that doesn't need to be in the repo, out of the repo, and to disable tests that are redundant or only need to be run in very specific cases.

#### Changes
- [x] Move scripts folder to another repo
  * _DONE_ New repo: [synthetix-cli](https://github.com/Synthetixio/synthetix-cli)
  * _MERGED_ [PR: Move scripts folder to its own repo](https://github.com/Synthetixio/synthetix/pull/807)
- [x] Improve synthetix-cli by adding prettier and a bin file
  * _DONE_ Applied the js template setup to the repo
  * _DONE_ Made interactive-ui.js de default bin. I.e. you can do npx synthetix and jump into the interactive ui.
- [x] Reorg ci jobs and workflows for more accurate and less intrussive ci usage
  * _IMPLEMENTED_ [Proposal DIP #1](https://docs.google.com/document/d/13JWUNFYiVSfyzCkjtgnUpGWCO-88jC-jvqWYupkLgiU/edit#heading=h.pn48zibvcm2q), [Analysis spreadsheet](https://docs.google.com/spreadsheets/d/1tqwphpmGfl1D4kRfHlzcn5PRggeJ6U9uDlEF-kNVxKo/edit#gid=0)
  * _MERGED_ [Refactored CircleCI workflows #837](https://github.com/Synthetixio/synthetix/pull/837)
  * _DONE_ Deprecate testnet tests (replaced by prod tests)
- [x] Use Jakub's node for CI prod tests
  * _SYNCED_ Sync node
  * _DONE_ What are the implications of having a mainnet only provider in CI? Should we go mainnet only? Or add a new PROVIDER_URL_MAINNET that will be used instead of PROVIDER_URL whenever available?
  * _MERGED_ [PR Use preferred mainnet provider](https://github.com/Synthetixio/synthetix/pull/826)
  * _DONE_ Add PROVIDER_URL_MAINNET in our ci settings
- [x] Make sure prod tests are not failing on develop
  - _DONE_ Study why tests are failing
  - _MERGED_ [PR: Minor bugfix on prod tests #831](https://github.com/Synthetixio/synthetix/pull/831)
  - _CLOSED_ PR below fixes the same problem 👇 [PR: Bugfix for PROVIDER_URL_MAINNET #834](https://github.com/Synthetixio/synthetix/pull/834)
  - _MERGED_ [Upgrading buidler-truffle5 to fix coverage issues #833](https://github.com/Synthetixio/synthetix/pull/833)
- [x] Implement cgewecke's multi gas report feature.
  * _[ISSUE CLOSED]_ Issue in eth-gas-reporter: [Ability to display two different checks #217](https://github.com/cgewecke/eth-gas-reporter/issues/217#issuecomment-708094466)
  * _MERGED_ [PR: Implements two gas reports...](https://github.com/Synthetixio/synthetix/pull/805)
- [x] Rename circleci files with job-xxx, cmd-xxx, etc
  * _MERGED_ [PR: Prefixes circleci file names](https://github.com/Synthetixio/synthetix/pull/808)
- [x] Bug: When CI test-prod-gas fails, workflow does not fail
  * Eg. [this circleci run](https://app.circleci.com/pipelines/github/Synthetixio/synthetix/4075/workflows/cf1728df-edcd-44e2-842a-59184378973d/jobs/27939)
  * _MERGED_ [PR: Makes CI fail when prod tests on mainnet fail #809](https://github.com/Synthetixio/synthetix/pull/809)
