### ISSUE TITLE
[EPIC] Escrow migration

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#138]
- [ ] Research data migration technique (can we send that much data)
- [ ] Implement it on both L1 and L2
- [x] (Jacko) [Working document on the L1 requirements](https://docs.google.com/document/d/1p3BDyvKYNxxvkkh3fMD8r9w6u9WMESfeeU8UEm4Msc0/edit?ts=5f88df00#)
- [ ] (Jacko) SIP: https://github.com/Synthetixio/SIPs/pull/270
- [ ] (Jacko) New Escrow contract that supports removal of entries for migration to L2
