### ISSUE TITLE
[EPIC] vTokens

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#141]
- [x] SIP created ([SIP-89](https://sips.synthetix.io/sips/sip-89))
- [x] [VirtualToken gist](https://gist.github.com/justinjmoses/6ffc0f2a511c8907b88039fbd7feb400)
- [x] Estimate gas impacts of new `VirtualSynth` contract deployment (from 500k to about 1.5m)
- [x] Estimate gas impacts of a `VirtualToken` as well
- [x] Add `VirtualToken` gist to SIP
- [ ] Implementation and testing
- [ ] Gas optimizations for `ViritualSynth`
- [ ] Deployment onto kovan for third party testing

Current working branch: https://github.com/Synthetixio/synthetix/compare/sip-89-virtual-synths#diff-4245e5ffd4d26871ad97996d5a56aa4003c680cc5a05084ef5d156ccddaa209d
