### ISSUE TITLE
[EPIC] Test suite in OVM mode

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#145]
- [ ] Running tests with OVM flag
  - [x] _KEVIN_ Will let us know when this is ready to work again
  - [ ] Try out and ensure they pass locally
  - [ ] Update CI to run these tests, ideally not in a frequent workflow
