### ISSUE TITLE
[EPIC] Discussion with the Optimism team about potential asynch failures and how to address them

### ISSUE THREAD

**Issue by i-stam** [Synthetixio/synthetix-pm#148]
- [x] What happens if the relayed message fails (e.g. gasLimit exceeded). Which is the best mechanism for recovering from such failures? Does Optimism provide one?
  UPDATE:  Optimism provides a replay mechanism for replaying messages safely in L2.
- [x] What are the implications of sending multiple messages?
  * Kevin's reply: "_It should be fine to do! one implication is that the L1->L2 messages will be relayed to L2 in multiple L2 txs, this just means we’ll have to make sure the frontend waits until ALL messages are relayed instead of just one.
And you could have instances where some of the messages revert and some don’t, in which case you would just have to replay the ones that reverted_"
- [x] Assess the xDomain gasLimit value implications.
  * ~make it parameterizable (e.g. move it to system settings)~ 
  * Use multiple constants.
