### ISSUE TITLE
[EPIC] Finish phase C deployment

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#149]
- [x] Connect new messengers
- [x] Test withdrawals
- [ ] Working front end
- [x] Drop another 50k rewards
- [ ] Handle comms
