### ISSUE TITLE
Test relay owner migration

### ISSUE THREAD

**Issue by eternauta1337** [Synthetixio/synthetix-pm#205]
### TODO
- [x] @leomassazza Write new accept-relay-script
- [ ] @Mati Modify nominate.js script to target nominateNewOwner on L2 via the relay (initiatizeRelay)

### Runsheet
- [ ] Prepare fresh instances
  - [ ] Deploy new fresh instance in kovan L1
  - [ ] Deploy new fresh instance in kovan-ovm L2
  - [ ] Connect instances
- [ ] Change owner on L2
  - [ ] Run nominate.js in instance to nominate OwnerRelayOnOptimism
  - [ ] Run accept-relay-owner.js in instance <================ New
  - [ ] Verify that the OwnerRelayOnOptimism is the new owner
  - [ ] Manual tests on L2
- [ ] Test the relay by changing a setting
  - [ ] Use L1 multisig to relay a setting change in L2
- [ ] Change owner on L2 back, via the relay
  - [ ] Use nominate-owner.js to nominate an EAO in L2 <========== Modify
  - [ ] Verify EOA is nominated in L2
  - [ ] Run owner.js on L2 to acceptOwnership in L2

**Comment by mjlescano** [comment]
👍
